# Generated by Django 5.2.10 on 2026-01-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('station_id', models.CharField(max_length=64)),
                ('temp_c', models.FloatField()),
                ('precip_mm', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'measurements',
                'indexes': [models.Index(fields=['station_id', 'date'], name='measurement_station_3e31e6_idx'), models.Index(fields=['date'], name='measurement_date_58d7b1_idx')],
                'constraints': [models.UniqueConstraint(fields=('station_id', 'date'), name='uniq_measurements_station_date')],
            },
        ),
        migrations.CreateModel(
            name='StagingMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('station_id', models.CharField(blank=True, max_length=64, null=True)),
                ('temp_c', models.FloatField(blank=True, null=True)),
                ('precip_mm', models.FloatField(blank=True, null=True)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'staging_measurements',
                'indexes': [models.Index(fields=['station_id', 'date'], name='staging_mea_station_794fcb_idx')],
            },
        ),
    ]
