# Generated by Django 5.2.10 on 2026-02-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_alter_measurement_id_alter_stagingmeasurement_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='measurement',
            name='uniq_measurements_station_date',
        ),
        migrations.RemoveIndex(
            model_name='measurement',
            name='measurement_station_3e31e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='measurement',
            name='measurement_date_58d7b1_idx',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='precip_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temp_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagingmeasurement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.UniqueConstraint(fields=('station_id', 'date'), name='uniq_station_date'),
        ),
        migrations.AlterModelTable(
            name='measurement',
            table=None,
        ),
    ]
