# Generated by Django 6.0.1 on 2026-02-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0003_remove_measurement_uniq_measurements_station_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="station_id",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="stagingmeasurement",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["station_id", "date"], name="metrics_mea_station_f0c364_idx"
            ),
        ),
    ]
