# Generated by Django 6.0.1 on 2026-02-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0004_alter_measurement_date_alter_measurement_id_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="measurement",
            new_name="idx_measure_station_date",
            old_name="metrics_mea_station_f0c364_idx",
        ),
        migrations.RenameIndex(
            model_name="stagingmeasurement",
            new_name="idx_stage_station_date",
            old_name="staging_mea_station_794fcb_idx",
        ),
        migrations.RemoveField(
            model_name="stagingmeasurement",
            name="loaded_at",
        ),
        migrations.AlterField(
            model_name="measurement",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="station_id",
            field=models.CharField(max_length=64),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(fields=["station_id"], name="idx_measure_station"),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(fields=["date"], name="idx_measure_date"),
        ),
        migrations.AddIndex(
            model_name="stagingmeasurement",
            index=models.Index(fields=["station_id"], name="idx_stage_station"),
        ),
        migrations.AddIndex(
            model_name="stagingmeasurement",
            index=models.Index(fields=["date"], name="idx_stage_date"),
        ),
        migrations.AlterModelTable(
            name="stagingmeasurement",
            table=None,
        ),
    ]
