# Generated by Django 6.0.1 on 2026-02-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "metrics",
            "0005_rename_metrics_mea_station_f0c364_idx_idx_measure_station_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="stagingmeasurement",
            name="idx_stage_station_date",
        ),
        migrations.RenameIndex(
            model_name="measurement",
            new_name="idx_meas_station",
            old_name="idx_measure_station",
        ),
        migrations.RenameIndex(
            model_name="measurement",
            new_name="idx_meas_date",
            old_name="idx_measure_date",
        ),
        migrations.RenameIndex(
            model_name="measurement",
            new_name="idx_meas_station_date",
            old_name="idx_measure_station_date",
        ),
        migrations.AlterField(
            model_name="measurement",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="precip_mm",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="station_id",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="temp_c",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="stagingmeasurement",
            name="date",
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagingmeasurement",
            name="precip_mm",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="stagingmeasurement",
            name="station_id",
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="stagingmeasurement",
            name="temp_c",
            field=models.FloatField(null=True),
        ),
    ]
